cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'curl'
brew 'flow'
brew 'freetype'
brew 'git'
brew 'go'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'macvim'
brew 'openssl'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pygments'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'ripgrep'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'tldr'
brew 'unrar'
brew 'watchman'
brew 'wget'
brew 'yarn', args: ['without-node']
brew 'youtube-dl'
brew 'z'

cask '1password'
cask 'brave-browser'
cask 'docker'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'postico'
cask 'postman'
cask 'rectangle'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'vlc'
cask 'xquartz'
